# configuration for when running if __name__ == "__main__": in main.py

target_language: Japanese
native_language: English

# Which fields do you want to generate?
wanted_fields:
  synonyms: false
  test: true
  explanation: false
  first_example: false
  second_example: false
  hint: false
  definition: false
  grammar: false
  conjugation: false
  long_test_message: false
  

