# configuration for when running if __name__ == "__main__": in main.py

target_language: Japanese
native_language: English

# Which fields do you want to generate?
wanted_fields:
  synonyms: true
  test: true
  explanation: true
  first_example: true
  second_example: true
  hint: true
  definition: true
  grammar: true
  conjugation: true
  long_test_message: false
  
column_names:
  - ID
  - word_or_phrase
  - short_phrase
  - short_translation
  - word
  - stem
  - word_type
  - NAN
  - word_translation
  - website
  - language
  - translation_language
  - romaji
  - long_romaji
  - time_stamp
  - movie_code
  - source
  - date
  - long_phrase
  - machine_translation
  - human_translation
  - first_jpg
  - second_jpg
  - audio