# basically this just a library of prompts. 
# Different languages contain different messages, that explain diferent aspects of these languages

German: 
  cases: explain the use of cases in this sentence
  grammar: >
    "For example for the sentence: 
    'In einem Haus leben Menschen': 
    - In: in (inside) 
    - einem Haus:  'Einem' indefinite article, dative, neuter nouns, ‘das Haus'= house 
    - leben: 'to live', 3 ps. plural (lebe, lebst, lebt, leben, lebt, leben) 
    - Menschen: die Menschen der Mensch' = ‘people' or 'humans'. 
    / 2nd example: ‘Ich mag keine Äpfel’: 
    - Ich: I, (Me) 
    - mag: mögen =‘to like’ (mag, magst, mag, mögen, mögt, mögen), present tense (+ accusative) 
    - keine: 'no' - negation article, accusative case, plural 
    (because 'Äpfel' is plural and accusative reflects the direct object being negated). 
    - Äpfel: 'apples’, der Apfel, die Äpfel, accusative"
  conjugation: >
    "For example for the sentence: 
    'In einem Haus leben Menschen': 
    - In: in (inside) 
    - einem Haus:  'Einem' indefinite article, dative, neuter nouns, ‘das Haus'= house  
    - leben: 'to live', 3 ps. plural (lebe, lebst, lebt, leben, lebt, leben) 
    - Menschen: die Menschen der Mensch' = ‘people' or 'humans'. 
    / 2nd example: ‘Ich mage keine Äpfel’: 
    - Ich: I, (Me) 
    - mag: mögen =‘to like’ (mag, magst, mag, mögen, mögt, mögen), present tense (+ accusative) 
    - keine: 'no' 
    - negation article, accusative case, plural 
    (because 'Äpfel' is plural and accusative reflects the direct object being negated). 
    - Äpfel: 'apples’, der Apfel, die Äpfel, accusative"  
Japanese: 
  general: Please always provide furigana, in square brackets [like this] and with a blank space 
    before the compound word. For example 漢字[かんじ] or 人間[じんかん].
# TODO ChatGPT should generate furigana (only works properly with GPT4o)
  grammar: >
    "For example for the sentence: 'クツなんか持って どうすんのさ 靴下も': 
    クツなんか: クツ = くつ　(shoes),　何か –> なんか; something, shoething, shoethingy<br> 
    持って: 持つ, to hold, to have<br> 
    どうすんの: 'What should I do?'; どうする, の = question marker<br> 
    さ: emphasis.<br> 靴下: Socks<br> も: too<br> 
    Another example: 'あんたも気きまぐれに手てえ出だして 人ひとの仕事しごとをとっちゃならねえ 働はたらかなきゃな 
    こいつらの魔法まほうは消きえちまうんだ' 
    あんたも: あんた = あなた<br> 
    気きまぐれに: Whimsically (気まぐれ = whim, に = adverbial particle)<br> 
    手てえ出だして: 手出す = to put out one's hand, てえ = colloquial form of ている, Put your hand out, 出す, 出して<br> 
    人ひとの: Other people's (人の = 人の, の = possessive particle)<br> 
    仕事しごとを: 仕事 = work<br> 
    とっちゃならねえ: とる + ちゃ + ならない = とってはならない(negative potential form), ちゃ = ては contraction -> とっては -> とっちゃ 'Must not take'<br> 
    働はたらかなきゃな: Have to work (働く + ない + なければ + な, contraction of なければならない)<br> 
    こいつらの: Their (こいつら = these, の = possessive particle)<br> 
    魔法まほうは: Magic (魔法 = magic, は = topic marker)<br> 
    消きえちまうんだ: Will disappear (消える + ちまう + んだ, ちまう = contraction of てしまう, んだ = explanatory particle)<br>" 
  conjugation: >
    "For example for たべる:　食べる, 食べて、食べた、食べない、食べなかった、食べている、食べていた、食べていない、食べていなかった
French: 
  synonyms: "For example a translation for 'arbre': tree."
  first_example: "Like: 'J'aime manger des fruits。<br>I like to eat fruits.' "
  second_example: "Like 'J'aime pas ce mec<br>I don't like this guy'"
  explanation: "For example 'maison: ein Ort an dem Menschen leben.'"
  hint: "For example 'essen: to eat'."
  definition: "For example: 'Haus: ein Ort an dem Menschen leben.'"
  grammar: >
    "For example for the sentence: 
    'Le président vit dans une maison': 
    - Le président: The president 
    - vit: lives, 3rd person singular of the verb 'vivre' 
    - dans: in 
    - une maison: a house 
    / 2nd example: 'J'aime pas ce type de musique': 
    - J'aime pas: Je n'aime pas [Je ne aime pas] = I don't like 
    - type de musique: type of music"
  conjugation: >
    "For example for the sentence: 
    'Le président vit dans une maison': 
    - Le président: The president 
    - vit: 3. ps. vivre = to live (vis, vis, vit, vivons, vivez, vivent)
    - dans: in 
    - une maison: a house 
    / 2nd example: 'J'aime pas ce type de musique': 
    - J'aime pas: Je n'aime pas [Je ne aime pas] = I don't like, aimer: to like (aime, aimes, aime, aimons, aimez, aiment) 
    - type de musique: type of music"
Italian:
  synonyms: "For example a translation for 'albero': tree."
  first_example: "Like: 'Mi piace mangiare la frutta.<br>I like to eat fruit.' "
  second_example: "Like 'Non mi piace questo ragazzo'<br>I don't like this guy'"
  explanation: "For example 'casa: un luogo dove vivono le persone.'"
  hint: "For example 'mangiare: to eat'."
  definition: "For example: 'casa: un luogo dove vivono le persone.'"
  grammar: >
    "For example for the sentence: 
    'Il presidente vive in una casa': 
    - Il presidente: The president 
    - vive: 3. ps. 'vivere': to live (vivo, vivi, vive, viviamo, vivete, vivono) 
    - in: in 
    - una casa: a house 
    / 2nd example: 'Non mi piace questo genere di musica': 
    - Non mi piace: I don't like (mi piace, ti piace, gli/le piace, ci piace, vi piace, gli/le piace) 
    - questo genere di musica: this genre of music"
  conjugation: >
    "For example for the sentence: 
    'Il presidente vive in una casa': 
    - Il presidente: The president 
    - vive: 3. ps. 'vivere': to live (vivo, vivi, vive, viviamo, vivete, vivono) 
    - in: in 
    - una casa: a house 
    / 2nd example: 'Non mi piace questo genere di musica': 
    - Non mi piace: I don't like (mi piace, ti piace, gli/le piace, ci piace, vi piace, gli/le piace) 
    - questo genere di musica: this genre of music"