# This file contains the messages that are sent to the user during the different stages of the conversation.

anki_image_pattern: <img src="{{first_jpg}}"><img src="{{second_jpg}}">
anki_sound_pattern:  '[sound:{{audio}}]'
test: 
  "Say 'test'"
long_test_message:
  "Write a story that takes you 20 seconds to write! 
  I am testing something here with the chatGPT API call timeout. 
  You need to write a long story for me, so that the API call lasts at least 15 seconds."
test: say 'test'
grammar: 
  "First off: be EXTREMELY concise! Always provide the answer in {{native_language}}.
  Don't answer in whole sentences, only provide short notes! 
  Provide me with a brief explanation of the different grammatical elements in '{{short_phrase}}'. 
  Put <br> tags after every note."

# Example message that asks for synonyms in target_language, explanation in native_language, hint in native language, example sentence in target_language
general: 
  "I will provide you with a dataframe, containing pairs of sentences and words, where the word always appears in the sentence. 
  Provide me with a table, that contains following information for each pair:
  \n
  - Synonyms for the word in {{target_language}}.
  - A brief explanation of word in {{native_language}} (4 words).
  - A hint for word in {{native_language}}, short (4 words), paraphrasing the word? 
  I want to be able to guess the word by reading the hint, but the hint should never include the word.
  - An example sentence in {{target_language}}.
  \n
  The names of the columns from the table should be word, sentences 
  (just keep the original values from the dataframe I provided you with)
  synonyms, explanation, hint, example, example_translation.
  \nHere is the dataframe: 
  \n{{dataframe}}"

# TODO message needs to be customizable...
general_: 
  "I will provide you with a dataframe, containing pairs of sentences and words, where the word always appears in the sentence. 
  Provide me with a table, that contains following information for each pair:
  \n
  {{synonyms}}
  - Synonyms for the word in {{target_language}}.
  - A brief explanation of word in {{native_language}} (4 words).
  - A hint for word in {{native_language}}, short (4 words), paraphrasing the word? 
  I want to be able to guess the word by reading the hint, but the hint should never include the word.
  - An example sentence in {{target_language}}.
  \n
  The names of the columns from the table should be word, sentences 
  (just keep the original values from the dataframe I provided you with)
  synonyms, explanation, hint, example, example_translation.
  \nHere is the dataframe: 
  \n{{dataframe}}"

# NOTE unnecessary for Japanese
word_type: 
  "Please provide me with following information depening on what type of word '{{word}}' is:
  - If '{{word}}' is a verb, provide me with the conjugation of '{{word}}'.
  - If '{{word}}' is an adjective, provide me with the feminine, masculine and plural forms of '{{word}}'.
  - If '{{word}}' is a noun, provide me with the plural form of '{{word}}' and it's article."



